name: Continuous integration

on:
  push:
    branches: [ 'main' ]
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: 3.12

      - uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/*-requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install dependencies
        run: make install_deps
        if: steps.cache.outputs.cache-hit != 'true'

      - name: Make .env file
        run: make env_file

      - name: Run test suite with pytest
        run: make test

      - name: Run mypy
        if: success() || failure()
        run: make mypy

      - name: Run ruff formatter
        if: success() || failure()
        run: make format

      - name: Run ruff checker
        if: success() || failure()
        run: make check
